### PR TITLE
Compile correctly with dovecot 2.2.x and 2.3.x

### LINKED ISSUE #14: elasticsearch-conn.c:87:40: error: ‘struct http_url’ has no member named ‘host’; did you mean ‘port’?
```
elasticsearch-conn.c: In function ‘elasticsearch_connection_init’: 
elasticsearch-conn.c:87:40: error: ‘struct http_url’ has no member named ‘host’; did you mean ‘port’?  
     conn->http_host = i_strdup(http_url->host.name);                
                                        ^~
```

Building today's `master` b4c50447 on Gentoo. Not sure yet which library is causing this.

### PR DESCRIPTION
**Pull request by infernix**
Should fix #14 and is a minor improvement on 03d1b8e8ca38eed52332dbc79a260f5b1b31c35a

### CODE REVIEW

**Comment by atkinsj** [comment]
Thanks for doing all this work! LGTM on 2.3.3.
