### ISSUE TITLE
Error compiling on ubuntu

### ISSUE THREAD

**Issue by bernardpazio** [ascendantcom/fts-elasticsearch#10]
```
elasticsearch-conn.c:87:40: error: 'struct http_url' has no member named 'host_name'
     conn->http_host = i_strdup(http_url->host_name);
```

**Comment by atkinsj** [comment]
I haven't updated this for the last few Dovecot releases due to time on other projects; I'll try to make some time to get around to this in the next few days but no guarantees.

It looks like there's been a re-write of the HTTP API in Dovecot which we use to hit ES so I'll see how much work it is to switch over.

**Comment by Ch00k** [comment]
Getting the same error trying to compile against Dovecot 2.3.0 on Gentoo.

**Comment by archont00** [comment]
The plugin source was updated to use `host.name` now. But that fails with dovecot 2.2.32.1
```
elasticsearch-conn.c:87:42: error: ‘struct http_url’ has no member named ‘host’; did you mean ‘port’?
     conn->http_host = i_strdup(http_url->host.name);
                                          ^~~~
                                          port
```
Compiles fine with dovecot 2.3.1

**Comment by atkinsj** [comment]
I'll update the doc to note that the most recently supported version is 2.2.32.1 but I'm happy to take a pull request if someones wants to #ifdef this on DOVECOT_VERSION to make it backwards compatible.
